import { _decorator } from 'cc';

// We create an enum for our text "keys". This prevents typos.
export enum ETextKey {
    PLAY,
    RESTART,
    JUMP,
    POWERUP_SPEED,
    POWERUP_MAGNET,
    POWERUP_CHILLIES,
    ENGLISH,
    HINDI,
    HIGH_SCORE,
    INFO_1_TITLE,
    INFO_1_TITLE1,
    INFO_1_DESC,
    INFO_2_TITLE,
    INFO_2_TITLE1,
    INFO_2_DESC,
    INFO_3_TITLE,
    INFO_3_TITLE1,
    INFO_3_DESC,
    HOW_TO_PLAY,
    ARABIC,
    SPINNEYS_TAG,
    COPY_CODE,
    INFO_4_TITLE,
    TAG_LINE_2,
    BONUS_INFO,
    // Add any new text keys here
}

// This is our translation database.
// 'en' = English, 'hi' = Hindi, 'en_HI' = Hinglish
export const localizationData = {
    'en': {
        [ETextKey.PLAY]: "PLAY",
        [ETextKey.RESTART]: "RESTART",
        [ETextKey.JUMP]: "JUMP",
        [ETextKey.POWERUP_SPEED]: "SPEED",
        [ETextKey.POWERUP_MAGNET]: "MAGNET",
        [ETextKey.POWERUP_CHILLIES]: "CHIPS",
        [ETextKey.ENGLISH]: "ENGLISH",
        [ETextKey.HINDI]: "हिन्दी",
        [ETextKey.HIGH_SCORE]: "HIGH SCORE !",
        [ETextKey.INFO_1_TITLE]: "LIVES TO\nEAT CHIPS",
        [ETextKey.INFO_1_TITLE1]: "SWIPE TO MOVE,\nTAP TO JUMP",
        [ETextKey.INFO_1_DESC]: "AVOID OBSTACLES AND\nCOLLECT OUR TASTY CHIPS",
        [ETextKey.INFO_2_TITLE]: "NEW PREMIUM\nFLAVOURS",
        [ETextKey.INFO_2_TITLE1]: "NEW PREMIUM\nFLAVOURS !",
        [ETextKey.INFO_2_DESC]: "OUR 4 PREMIUM FLAVOURS\nGIVES YOU THAT TASTY\nADVANTAGE!",
        [ETextKey.INFO_3_TITLE]: "SPINNEY'S\nDISCOUNT",
        [ETextKey.INFO_3_TITLE1]: "SUPER CHILLY\nDISCOUNTS",
        [ETextKey.INFO_3_DESC]: "UPTO 30% OFF FOR YOUR\nNEXT PURCHASE FROM\nSPINNEYS.",
        [ETextKey.HOW_TO_PLAY]: "HOW TO PLAY",
        [ETextKey.ARABIC]: "عربي",
        [ETextKey.SPINNEYS_TAG]: "REDEEM THIS CODE AT SPINNEYS FOR A DISCOUNT",
        [ETextKey.COPY_CODE]: "COPY CODE",
        [ETextKey.INFO_4_TITLE]: "SHIELD",
        [ETextKey.TAG_LINE_2]: "Hunter's Gourmet Truffle flavors are always available at Spinneys!",
        [ETextKey.BONUS_INFO]: "Collect all four FLAVOURS to get a BONUS 50 points",

    },
    'hi': {
        [ETextKey.PLAY]: "खेलें",
        [ETextKey.RESTART]: "फिर से शुरू करें",
        [ETextKey.JUMP]: "जम्प",
        [ETextKey.POWERUP_SPEED]: "स्पीड",
        [ETextKey.POWERUP_MAGNET]: "मैगनेट",
        [ETextKey.POWERUP_CHILLIES]: "चिलीज़",
        [ETextKey.ENGLISH]: "ENGLISH",
        [ETextKey.HINDI]: "हिन्दी",
        [ETextKey.HIGH_SCORE]: "उच्च स्कोर !",
        [ETextKey.INFO_1_TITLE]: "मिर्च खाने के\nलिए जीता है",
        [ETextKey.INFO_1_DESC]: "बाधाओं से बचें और\nमिर्च इकट्ठा करें",
        [ETextKey.INFO_2_TITLE]: "नए प्रीमियम\nफ्लेवर",
        [ETextKey.INFO_2_DESC]: "हमारे नए मिर्च-युक्त\nस्वादों का उपयोग करें",
        [ETextKey.INFO_3_TITLE]: "स्पिनीज़ पर\nधिकतम छूट",
        [ETextKey.INFO_3_DESC]: "रोमांचक छूट जीतें\nऔर स्कोर साझा करें",
        [ETextKey.HOW_TO_PLAY]: "कैसे खेलने के लिए",
        [ETextKey.ARABIC]: "عربي",
        [ETextKey.SPINNEYS_TAG]: "REDEEM THIS CODE AT SPINNEY'S FOR DISCOUNTS",
    },
    'en_HI': {
        [ETextKey.PLAY]: "Khelo!",
        [ETextKey.RESTART]: "Phirse Khelo",
        [ETextKey.JUMP]: "JUMP",
        [ETextKey.POWERUP_SPEED]: "RAFTAAR",
        [ETextKey.POWERUP_MAGNET]: "CHUMBAK",
        [ETextKey.POWERUP_CHILLIES]: "Chillies",
        [ETextKey.ENGLISH]: "ENGLISH",
        [ETextKey.HINDI]: "HINGLISH",
        [ETextKey.HIGH_SCORE]: "HIGH SCORE !",
        [ETextKey.INFO_1_TITLE]: "life main\nmirchi bataro",
        [ETextKey.INFO_1_TITLE1]: "Mirchi batorne\nke 3 life",
        [ETextKey.INFO_1_DESC]: "Controls ke saath\nrukawaton se\nbacho aur\nmirchiyan batoro!",
        [ETextKey.INFO_2_TITLE]: "naye premium\nflavors",
        [ETextKey.INFO_2_TITLE1]: "Naye Premium\nFlavors",
        [ETextKey.INFO_2_DESC]: "Humare 3 naye\npremium flavors se\nmirchiyan batoro aur\nhigh score banao",
        [ETextKey.INFO_3_TITLE]: "adhiktam discount\nspinnys main",
        [ETextKey.INFO_3_TITLE1]: "Uttam\nBacchat!",
        [ETextKey.INFO_3_DESC]: "Humare discount\ncode se apni\nkhareedari par pao\n30% tak ki bacchat!",
        [ETextKey.HOW_TO_PLAY]: "Kaise Khele?",
        [ETextKey.ARABIC]: "عربي",
        [ETextKey.SPINNEYS_TAG]: "REDEEM THIS CODE AT SPINNEY'S FOR DISCOUNTS",
    },
    'ar': {
        [ETextKey.PLAY]: "العب",
        [ETextKey.RESTART]: "إعادة البدء",
        [ETextKey.JUMP]: "اقفز",
        [ETextKey.POWERUP_SPEED]: "سرعة",
        [ETextKey.POWERUP_MAGNET]: "مغناطيس",
        [ETextKey.POWERUP_CHILLIES]: "فلفل حار",
        [ETextKey.ENGLISH]: "ENGLISH",
        [ETextKey.HINDI]: "हिन्दी",
        [ETextKey.HIGH_SCORE]: "أعلى نتيجة !",
        [ETextKey.INFO_1_TITLE]: "حياة لجمع\nالفلفل الحار",
        [ETextKey.INFO_1_TITLE1]: "اجمع الفلفل أو\nمت وأنت تحاول",
        [ETextKey.INFO_1_DESC]: "استخدم عناصر التحكم\nلتجنب العقبات وجمع\nأكبر عدد ممكن من\nالفلفل الحار !",
        [ETextKey.INFO_2_TITLE]: "نكهات فاخرة\nجديدة",
        [ETextKey.INFO_2_TITLE1]: "نكهات فاخرة\nجديدة !",
        [ETextKey.INFO_2_DESC]: "استخدم نكهاتنا الـ3\nالفاخرة الجديدة لجمع المزيد\nمن الفلفل الحار وتحقيق\nأعلى نتيجة",
        [ETextKey.INFO_3_TITLE]: "خصم أقصى\nفي سبينيس",
        [ETextKey.INFO_3_TITLE1]: "خصومات حارة\nجداً",
        [ETextKey.INFO_3_DESC]: "احصل على خصم يصل\nإلى 30% على مشترياتك\nالقادمة في سبينيس\nمع أكواد الخصم الخاصة بنا",
        [ETextKey.HOW_TO_PLAY]: "كيفية اللعب",
        [ETextKey.ARABIC]: "عربي",
        [ETextKey.SPINNEYS_TAG]: "استخدم هذا الرمز في SPINNEY'S للحصول على خصومات",
        [ETextKey.COPY_CODE]: "نسخ الكود",
        [ETextKey.INFO_4_TITLE]: "درع",
        [ETextKey.TAG_LINE_2]: "نكهات Hunter's Gourmet Truffle متوفرة دائمًا في Spinneys!",
        [ETextKey.BONUS_INFO]: "اجمع كل النكهات الأربع لتحصل على مكافأة قدرها 50 نقطة",
    }
};
