import { _decorator } from 'cc';

// We create an enum for our text "keys". This prevents typos.
export enum ETextKey {
    ENGLISH,
    ARABIC,
    PLAY,
    HOW_TO_PLAY,
    HIGH_SCORE,
    RESTART,
    INSTRUCTION_1,
    INSTRUCTION_2,
    INFO_1_TITLE,
    INFO_1_DESC,
    INFO_2_TITLE,
    INFO_2_DESC,
    INFO_3_TITLE,
    INFO_3_DESC,
    POWERUP_1_TITLE,
    POWERUP_1_DESC,
    POWERUP_2_TITLE,
    POWERUP_2_DESC,
    POWERUP_3_TITLE,
    POWERUP_3_DESC,
    POWERUP_4_TITLE,
    POWERUP_4_DESC,
}

// This is our translation database.
// 'en' = English, 'hi' = Hindi, 'en_HI' = Hinglish
export const localizationData = {
    'en': {
        [ETextKey.ENGLISH]: "ENGLISH",
        [ETextKey.ARABIC]: "عربي",
        [ETextKey.PLAY]: "PLAY",
        [ETextKey.HOW_TO_PLAY]: "HOW TO PLAY",
        [ETextKey.HIGH_SCORE]: "YOUR HIGH SCORE !",
        [ETextKey.RESTART]: "RESTART",
        [ETextKey.INSTRUCTION_1]: "Liv Spheres\nto destroy\nexpenses!",
        [ETextKey.INSTRUCTION_2]: "Golden Liv\nblocks for\nextra coins!",
        [ETextKey.INFO_1_TITLE]: "Break Expenses!",
        [ETextKey.INFO_1_DESC]: "Use the Liv Sphere to\nbreak open the expense\nblocks and earn coins",
        [ETextKey.INFO_2_TITLE]: "Liv Power Ups!",
        [ETextKey.INFO_2_DESC]: "Liv's golden blocks will\ngive you extra coins and\nchance to win big!",
        [ETextKey.INFO_3_TITLE]: "Download LivX",
        [ETextKey.INFO_3_DESC]: "Download the Liv X app to\nearn 4% real rewards",
        [ETextKey.POWERUP_1_TITLE]: "Liv Goal",
        [ETextKey.POWERUP_1_DESC]: "Coin Magnet",
        [ETextKey.POWERUP_2_TITLE]: "Liv Card",
        [ETextKey.POWERUP_2_DESC]: "Double Bounce",
        [ETextKey.POWERUP_3_TITLE]: "Liv Prime",
        [ETextKey.POWERUP_3_DESC]: "2x Multiplier",
        [ETextKey.POWERUP_4_TITLE]: "Livionaire",
        [ETextKey.POWERUP_4_DESC]: "10x Coins",
    },
    'ar': {
        [ETextKey.ENGLISH]: "ENGLISH",
        [ETextKey.ARABIC]: "عربي",
        [ETextKey.PLAY]: "العب",
        [ETextKey.HOW_TO_PLAY]: "كيفية اللعب",
        [ETextKey.HIGH_SCORE]: "أعلى نتيجة !",
        [ETextKey.RESTART]: "إعادة البدء",
        [ETextKey.INSTRUCTION_1]: "كرات ليف \nلتدمير\n النفقات!",
        [ETextKey.INSTRUCTION_2]: "كتل ليف الذهبية\n للحصول على\n عملات إضافية!",
        [ETextKey.INFO_1_TITLE]: "تخفيض النفقات!",
        [ETextKey.INFO_1_DESC]: "استخدم كرة ليف لـ\nفتح النفقات\nالكتل وكسب العملات المعدنية",
        [ETextKey.INFO_2_TITLE]: "تعزيزات ليف!",
        [ETextKey.INFO_2_DESC]: "سوف كتل ليف الذهبية\nأعطيك عملات معدنية إضافية و\nفرصة للفوز الكبير",
        [ETextKey.INFO_3_TITLE]: "تنزيل LivX",
        [ETextKey.INFO_3_DESC]: "قم بتنزيل تطبيق Liv X لـ\nاحصل على 4% مكافآت حقيقية",
        [ETextKey.POWERUP_1_TITLE]: "هدف ليف",
        [ETextKey.POWERUP_1_DESC]: "مغناطيس",
        [ETextKey.POWERUP_2_TITLE]: "بطاقة ليف",
        [ETextKey.POWERUP_2_DESC]: "ارتداد مزدوج",
        [ETextKey.POWERUP_3_TITLE]: "لايف برايم",
        [ETextKey.POWERUP_3_DESC]: "مضاعف 2X",
        [ETextKey.POWERUP_4_TITLE]: "ليفيونيير",
        [ETextKey.POWERUP_4_DESC]: "10 عملات معدنية",
    }
};
